# Generated by Django 4.2.30 on 2026-04-27 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_perusahaan', models.CharField(max_length=255)),
                ('bidang_usaha', models.CharField(max_length=255)),
                ('lokasi_operasional', models.CharField(max_length=255)),
                ('jenis_pengadaan', models.CharField(blank=True, max_length=255)),
                ('range_nilai_proyek', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
