# Generated by Django 6.0.4 on 2026-05-14 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('whatsapp_number', models.CharField(max_length=30)),
                ('institution_email', models.EmailField(max_length=254, unique=True)),
                ('company_name', models.CharField(max_length=200)),
                ('business_field', models.CharField(max_length=200)),
                ('location_type', models.CharField(choices=[('indonesia', 'Indonesia'), ('international', 'Internasional')], default='indonesia', max_length=20)),
                ('province', models.CharField(blank=True, max_length=100, null=True)),
                ('city_or_regency', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
