# Generated by Django 6.0.4 on 2026-05-15 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_vendorprofile_delete_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='max_project_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='min_project_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='preferred_locations',
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='preferred_procurement_types',
            field=models.TextField(blank=True, default=""),
        ),
    ]
