# Generated by Django 4.2.30 on 2026-05-16 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_vendorprofile_max_project_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorprofile',
            name='preferred_locations',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='preferred_procurement_types',
            field=models.TextField(blank=True, default=''),
        ),
    ]
