# Generated by Django 4.2.30 on 2026-07-24 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_vendorprofile_dynamic_location_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorprofile',
            name='email_notifications_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
