# Generated by Django 4.2.30 on 2026-04-27 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_tender', models.CharField(max_length=50, unique=True)),
                ('nama_paket', models.TextField()),
                ('instansi', models.CharField(max_length=255)),
                ('tahapan', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
                ('nilai_hps', models.BigIntegerField(blank=True, null=True)),
                ('lokasi_pekerjaan', models.CharField(blank=True, max_length=255)),
                ('jenis_pengadaan', models.CharField(blank=True, max_length=255)),
                ('metode_pengadaan', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
