# Generated by Django 6.0.4 on 2026-04-30 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='nilai_pagu',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tender',
            name='peserta_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tender',
            name='tanggal_pembuatan',
            field=models.DateField(blank=True, null=True),
        ),
    ]
