# Generated by Django 6.0.4 on 2026-04-30 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0002_tender_nilai_pagu_tender_peserta_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='sumber_dana',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
