# Generated by Django 6.0.4 on 2026-04-30 04:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0003_tender_sumber_dana'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tender',
            name='jenis_kontrak',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='tender',
            name='kode_rup',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='tender',
            name='nama_paket_rup',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tender',
            name='satuankerja',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='tender',
            name='tahun_anggaran',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='tender',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tender',
            name='uraian_pekerjaan',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='tender',
            name='uraian_pekerjaan_nama_file',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
