# Generated by Django 6.0.4 on 2026-05-06 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0004_tender_created_at_tender_jenis_kontrak_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='detail_url',
            field=models.URLField(blank=True),
        ),
    ]
