# Generated by Django 4.2.30 on 2026-05-16 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0006_tenderbookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='klpd_instansi',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='tender',
            name='lokasi_pekerjaan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tender',
            name='nama_paket',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tender',
            name='nama_paket_rup',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tender',
            name='uraian_pekerjaan_nama_file',
            field=models.TextField(blank=True, null=True),
        ),
    ]
