# Generated by Codex on 2026-05-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenders", "0007_tender_klpd_instansi_alter_tender_lokasi_pekerjaan_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tender",
            name="lpse_kd",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tender",
            name="lpse_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="tender",
            name="lpse_detail_url",
            field=models.URLField(blank=True, default=""),
        ),
    ]
