# Generated by Django 4.2.30 on 2026-06-18 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0015_inaproc_realisasi_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tender',
            name='detail_url',
            field=models.URLField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='tender',
            name='instansi',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tender',
            name='jenis_kontrak',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tender',
            name='jenis_pengadaan',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tender',
            name='klpd_instansi',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tender',
            name='kode_rup',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tender',
            name='metode_pengadaan',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tender',
            name='status',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tender',
            name='sumber_dana',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tender',
            name='tahapan',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tender',
            name='tahun_anggaran',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tender',
            name='uraian_pekerjaan',
            field=models.URLField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
