# Generated by Django 4.2.30 on 2026-06-23 04:59

from django.db import migrations, models
from django.db.models import Q


def normalize_existing_sources(apps, schema_editor):
    Tender = apps.get_model("tenders", "Tender")
    Tender.objects.filter(data_source__in=["inaproc_realisasi_csv", "inaproc_realisasi_detail_csv"]).update(
        data_source="REALISASI"
    )
    Tender.objects.filter(data_source__in=["spse", "spse_inaproc_datatables"]).update(data_source="SPSE")
    Tender.objects.filter(data_source__in=["lkpp", "lkpp_api"]).update(data_source="LKPP_API")

    blank_source = Q(data_source__isnull=True) | Q(data_source="")
    spse_signal = Q(lpse_slug__gt="") | Q(lpse_detail_url__contains="spse.inaproc.id") | Q(detail_url__contains="spse.inaproc.id")
    realisasi_signal = Q(kode_paket__isnull=False) | Q(status_paket__isnull=False) | Q(nama_penyedia__isnull=False) | Q(total_nilai__isnull=False)

    Tender.objects.filter(blank_source & spse_signal).update(data_source="SPSE")
    Tender.objects.filter(blank_source & realisasi_signal).update(data_source="REALISASI")
    Tender.objects.filter(data_source="REALISASI").filter(spse_signal).update(data_source="MIXED")


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0017_inaprocinstansi'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='dokumen',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='tender',
            name='metode_kualifikasi',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tender',
            name='metode_pemilihan',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tender',
            name='nilai_kontrak',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.RunPython(normalize_existing_sources, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='tender',
            name='data_source',
            field=models.CharField(blank=True, choices=[('SPSE', 'SPSE'), ('REALISASI', 'INAPROC Realisasi'), ('LKPP_API', 'LKPP API'), ('MIXED', 'Mixed')], default='SPSE', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tender',
            name='kode_tender',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='tender',
            name='sumber_dana',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddIndex(
            model_name='tender',
            index=models.Index(fields=['data_source', 'status'], name='tenders_src_status_idx'),
        ),
        migrations.AddIndex(
            model_name='tender',
            index=models.Index(fields=['lpse_slug', 'status'], name='tenders_lpse_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='tender',
            constraint=models.UniqueConstraint(fields=('kode_tender', 'lpse_slug'), name='unique_tender_kode_lpse_slug'),
        ),
    ]
