# Generated by Django 4.2.30 on 2026-07-24 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0020_tendernotificationemaillog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tender',
            name='raw_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
